server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssmdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    data-username: root
    data-password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #指定映射文件路径
  mapper-locations: clsspath:/myresouces/mapper/*.xml
  #给包起别名
  #type-aliases-package: